export enum ICONS {
  BELL = 'bell',
  CALENDAR_MINUS = 'calendar-minus',
  GRID = 'grid',
  MESSAGE_CIRCLE_DOTS = 'message-circle-dots',
  QUESTION_ROUND = 'question-round',
  USER = 'user',
  CHEVRON_LEFT_SMALL = 'chevron-left-small',
  CHEVRON_RIGHT_SMALL = 'chevron-right-small',
  FILTERS = 'filters',
  PLUS = 'plus',
  THE_SUM_OF = 'the-sum-of',
  EYS_OPEN = 'eye-open',
  KEY = 'key',
  MAIL = 'mail',
  PHONE = 'phone',
  USER_CIRCLE = 'user-circle',
}
