import { StyleSheet } from 'react-native';
import Color from 'color';
import { COLORS } from './colors';
import { Platform } from './platform';

export const DefaultTheme = {
  colors: {
    black: COLORS.BLACK,
    white: COLORS.WHITE,
    santas_gray: COLORS.SANTAS_GRAY,
    pale_sky: COLORS.PALE_SKY,
    spring_green: COLORS.SPRING_GREEN,
    cyan: COLORS.CYAN,
    blue: COLORS.BLUE,
    lightBlue: COLORS.LIGHT_BLUE,
    darkBlue: COLORS.DARK_BLUE,
    green: COLORS.GREEN,
    lightGreen: COLORS.LIGHT_GREEN,
    gray: COLORS.GRAY,
    gray2: COLORS.GRAY2,
    red: COLORS.RED,
    botticelli: COLORS.BOTTICELLI,
    darkGray: COLORS.DARK_GRAY,
    darkGray2: COLORS.DARK_GRAY_2,
    lightGray: COLORS.LIGHT_GRAY,
    lightGray2: COLORS.LIGHT_GRAY_2,
    inputBorder: COLORS.BLACK,
    inputLabel: COLORS.BLACK,
    inputPrefix: COLORS.BLACK,
    borderFocus: COLORS.BLACK,
    loading: COLORS.RED,
    overlayTopic: COLORS.OVERLAY_GREEN,
    yellow: COLORS.YELLOW,
    bgCall: COLORS.WHITE,
    bgActionPhone: COLORS.BG_ACTION_PHONE,
    text: COLORS.BLACK,
    bgSplashLinearGradient: [
      Color(COLORS.JAVA).alpha(0.4).toString(),
      Color(COLORS.WHITE).alpha(0.9).toString(),
      COLORS.WHITE,
    ],
    bgNewSplashLinearGradient: [
      Color(COLORS.WHITE).alpha(0).toString(),
      Color(COLORS.WHITE).alpha(0.9).toString(),
      COLORS.WHITE,
    ],
    logo: COLORS.MANDY,
    btnSignUp: COLORS.MANDY,
    unfilledColor: COLORS.MANDY,
    bgBtnLogin: COLORS.FUZZY_WUZZY,
    error: COLORS.FUZZY_WUZZY,
    mandy: COLORS.MANDY,
    grey: COLORS.GREY,
    primary: COLORS.MANDY,
    grey1: COLORS.EMPEROR,
    bgSwitch: COLORS.BG_SWITCH,
    mediumPurple: COLORS.MEDIUM_PURPLE,
    lightWisteria: COLORS.LIGHT_WISTERIA,
    mauve: COLORS.MAUVE,
    gradientQuizDefault: [
      Color(COLORS.JAVA).alpha(0.4).toString(),
      Color(COLORS.WHITE).alpha(0.9).toString(),
      COLORS.WHITE,
    ],
    bgProfile: COLORS.GALLERY,
    orange: COLORS.ORANGE,
    gallery: COLORS.GALLERY,
  },
  typography: StyleSheet.create({
    interRegular: {
      fontFamily: 'Inter-Regular',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interExtraLight: {
      fontFamily: 'Inter-ExtraLight',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interThin: {
      fontFamily: 'Inter-Thin',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interLight: {
      fontFamily: 'Inter-Light',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interMedium: {
      fontFamily: 'Inter-Medium',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interSemiBold: {
      fontFamily: 'Inter-SemiBold',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interExtraBold: {
      fontFamily: 'Inter-ExtraBold',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    interBlack: {
      fontFamily: 'Inter-Black',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
    inter: {
      fontFamily: 'Inter',
      fontSize: Platform.SizeScale(),
      color: COLORS.DARK_GRAY,
    },
  }),
};
